version: "3.6"

services: 

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:latest
    restart: always
    env_file: ./.env
    hostname: ${SERVER}
    ports:
      - '$GIT_LAB_SSH_PORT:22'
      - '$GIT_LAB_HTTP_PORT:80'
      - '$GIT_LAB_HTTPS_PORT:443'
    expose: 
    - ${GIT_LAB_HTTP_PORT}
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

  gitlab-runner:
    depends_on: 
      - gitlab
    container_name: runner
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock



      

