version: '3.6'

services:

  web:
    image: nginx
    volumes:
    - ./http/www/:/usr/share/nginx/html/
    ports:
    - ${HTTP_SERVER_PORT}:80
    environment:
    - NGINX_HOST=teste.local
    - NGINX_PORT=80
    networks:
      - network

  https-portal:
#   Definindo a versão do https-portal
    image: steveltn/https-portal:1
#   'Apontando' a pasta atual para o diretório /var/www/ dentro do container
    volumes:
      - "./certificados/:/var/lib/https-portal"
#   Apontando as portas 80 e 443 do container para as portas 80 e 443 da máquina
    ports:
      - '80:80'
      - '443:443'
#   Relacionando o container do https-portal com o servidor
    links:
      - web
    restart: always
#   Configurações de ambiente
    environment:
           DOMAINS: '${SERVER} -> http://web:80'
#     Definindo o ambiente como produção
      STAGE: 'production'
#     Impedindo a renovação ao subir o container
      FORCE_RENEW: 'false'
    networks:
      - network

  
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:latest
    restart: always
    env_file: ./.env
    hostname: ${SERVER}:${GIT_LAB_HTTP_PORT}
    ports:
      - ${GIT_LAB_SSH_PORT}:22
      - ${GIT_LAB_HTTP_PORT}:3080
      - ${GIT_LAB_HTTPS_PORT}:443
    expose: 
      - ${GIT_LAB_HTTP_PORT}
      - ${GIT_LAB_SSH_PORT}
    volumes:
      - ${GITLAB_HOME}/config:/etc/gitlab
      - ${GITLAB_HOME}/logs:/var/log/gitlab
      - ${GITLAB_HOME}/data:/var/opt/gitlab


  gitlab-runner:
    depends_on: 
      - gitlab
    container_name: runner
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  
  docker-registry:
    container_name: docker-registry
    image: registry:2
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./docker-registry/data:/data
      - ./certificados/default_server:/certs
    restart: always
    ports:
      - ${DOCKER_REGISTY}:5000
    expose: 
      - ${DOCKER_REGISTY}
      
networks:
  network:
