version: "3.3"

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:14.2.4-ee.0
    restart: always
    env_file: ./.env
    hostname: ${HOST}:${GITLAB_HTTP_PORT}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    ports:
      - ${GITLAB_SSH_PORT}:22
      - ${GITLAB_HTTP_PORT}:80
      - ${GITLAB_HTTPS_PORT}:443
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
