version: '3.6'

services:
  web:
    image: nginx
    container_name: web
    env_file: ./.env
    volumes:
    - ./http/www/:/usr/share/nginx/html/
    ports:
    - ${HTTP_SERVER_PORT}:80
    environment:
    - NGINX_HOST=${HOST}
    - NGINX_PORT=80
    networks:
      - network

  https-portal:
    image: steveltn/https-portal:1
    container_name: https
    env_file: ./.env
    volumes:
      - "./certificados/:/var/lib/https-portal"
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: '${HOST} -> http://web:80'
      STAGE: ${HTTPS_STAGE}
      FORCE_RENEW: 'false'
    networks:
      - network
networks:
  network:
