version: '3.6'

services: 
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    env_file: ./.env
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - ${JENKINS_SERVER_PORT}:50000
      - ${JENKINS_HTTP_PORT}:8080