version: "3.7"

services:
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    ports:
      - 2376:2376
    volumes:
      - ./jenkins-server/jenkins-docker-certs:/certs/client
      - ./jenkins-server/jenkins-docker-data:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - jenkins-net

  jenkins-blueocean:
    container_name: jenkins-blueocean
    image: jenkins-blueocean
    build: 
      context: ./dockerfiles
      dockerfile: Dockerfile.jenkins
    ports:
      - ${JENKINS_HTTP_PORT}:8080
      - ${JENKINS_JLP_PORT}:50000
    volumes:
      - ./jenkins-server/jenkins-data:/var/jenkins_home
      - ./jenkins-server/jenkins-docker-certs:/certs/client:ro
      - $HOME:/home
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    networks:
      - jenkins-net

networks:
  jenkins-net:
