version: '3.6'

services:
  portainer-server:
    env_file: ./.env
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --admin-password-file '/data portainer/ portainer/portainer-ce/senha-portainer'
    ports: 
      - ${PORTAINER_SERVER_PORT}:8000
      - ${PORTAINER_HTTP_PORT}:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_HOME}:/data portainer/ portainer/portainer-ce
