version: "3.3"

services:
  docker-registry:
    container_name: docker-registry
    image: registry:2
    env_file: ./.env
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./registry/data:/data
      - ./registry/certificados/default_server:/certs
    restart: always
    ports:
      - ${DOCKER_REGISTRY_PORT}:5000
    expose:
      - 5000
